### ISSUE TITLE
Bug with generating a list from yaml

### ISSUE THREAD

**Issue by Fusezion** [SkyCraft78/skript-storage#1]
Not really sure if this is much of a bug or just not proper usage on my end, but when I try to retreieve a list from a yml file and send it to the server it sends it as a whole instead of in a list of values, for example making a file with

```yaml
test:
  - 1
  - 2
  - 3
  - 4
  - 5
```
and using `send values "test" of "plugins/Skript/yaml/test.yml" as list` it for me returns nothing but using a list variable and sending it returns ``[1, 2, 3, 4, 5]`` instead of line by line

**Comment by SkyCraft78** [comment]
Hello 😄 
The `as list` mark has effect only when you set the node value, to save it as a list.
skript-storage will by itself convert the values to a list if there are multiple so you don't need that mark in that case.
However, it should return a property Skript list, and I could have made a mistake by returning the List's java type instead of the Skript one.
I will search deeper on my side, but could you try to remove the `as list` part in case of anything?

**Comment by SkyCraft78** [comment]
Okay, I finally got the way to reproduce it, and I have been fixed it.
In addition, if you wanna loop these multiple values, don't forget the `s` on `values`, it's now considered as a multiple values.
Thanks for the report 👍
